apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  hostPath: "/mnt/data/"