apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/mnt/data/"